import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" className="dark">
      <body className="min-h-screen grid grid-rows-[80px_1fr_auto]  dark:bg-zinc-800 dark:text-base-content">
        {children}
      </body>
    </html>
  );
}
